name = "FlatZinc"
uuid = "51d0216f-4a04-4f58-83ee-a6b62c27d29d"
authors = ["Hans Würfel <git@wuerfel.io> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[compat]
AbstractTrees = "0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
